//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mojang.escape.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.mojang.escape.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream altar {
            get {
                return ResourceManager.GetStream("altar", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream bosskill {
            get {
                return ResourceManager.GetStream("bosskill", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream click {
            get {
                return ResourceManager.GetStream("click", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream click2 {
            get {
                return ResourceManager.GetStream("click2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream crumble {
            get {
                return ResourceManager.GetStream("crumble", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap crypt {
            get {
                object obj = ResourceManager.GetObject("crypt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream cut {
            get {
                return ResourceManager.GetStream("cut", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream death {
            get {
                return ResourceManager.GetStream("death", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap dungeon {
            get {
                object obj = ResourceManager.GetObject("dungeon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap floors {
            get {
                object obj = ResourceManager.GetObject("floors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap font {
            get {
                object obj = ResourceManager.GetObject("font", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gamepanel {
            get {
                object obj = ResourceManager.GetObject("gamepanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream hit {
            get {
                return ResourceManager.GetStream("hit", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream hurt {
            get {
                return ResourceManager.GetStream("hurt", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream hurt2 {
            get {
                return ResourceManager.GetStream("hurt2", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ice {
            get {
                object obj = ResourceManager.GetObject("ice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap items {
            get {
                object obj = ResourceManager.GetObject("items", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream key {
            get {
                return ResourceManager.GetStream("key", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream kill {
            get {
                return ResourceManager.GetStream("kill", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ladder {
            get {
                return ResourceManager.GetStream("ladder", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap overworld {
            get {
                object obj = ResourceManager.GetObject("overworld", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream pickup {
            get {
                return ResourceManager.GetStream("pickup", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream potion {
            get {
                return ResourceManager.GetStream("potion", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream roll {
            get {
                return ResourceManager.GetStream("roll", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream shoot {
            get {
                return ResourceManager.GetStream("shoot", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap sky {
            get {
                object obj = ResourceManager.GetObject("sky", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream slide {
            get {
                return ResourceManager.GetStream("slide", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream splash {
            get {
                return ResourceManager.GetStream("splash", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap sprites {
            get {
                object obj = ResourceManager.GetObject("sprites", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap start {
            get {
                object obj = ResourceManager.GetObject("start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap temple {
            get {
                object obj = ResourceManager.GetObject("temple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream thud {
            get {
                return ResourceManager.GetStream("thud", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream treasure {
            get {
                return ResourceManager.GetStream("treasure", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap walls {
            get {
                object obj = ResourceManager.GetObject("walls", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
